on:
  pull_request:

jobs:
  Run-UVU-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: true
      - run: pnpm test
