on:
  pull_request:

jobs:
  Run-UVU-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Read .nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
