on:
  pull_request:

jobs:
  Run-UVU-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 15.14.0
      - run: npm ci
      - run: npm test