on:
  pull_request:

jobs:
  Run-UVU-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up node
        uses: dcodeIO/setup-node-nvm@master
        with: 
          node-version: ""
      - run: npm ci
      - run: npm test